- name: ec2
  hosts: aws_ec2
  become: true
  tasks: 
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd
    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
    - shell: echo "<h1>This is $(hostname -f)</h1>" > /var/www/html/index.html
