- name: ec2
  hosts: aws_ec2
  become: true
  tasks: 
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd
    - name: Enable service httpd
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
    - name: debug
      debug: var=ansible_hostname
    - name: echo
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        create: yes
        line: "<h1>This is {{ansible_hostname}}</h1>"
        insertbefore: BOF
